# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0002_temporarytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('I', 'Inconnu'), ('M', 'Homme'), ('F', 'Femme')], default='I', max_length=1),
        ),
    ]
