# Generated by Django 2.1.5 on 2019-03-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0002_actiontoken_temporarytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('I', 'Inconnu'), ('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True),
        ),
    ]
