# Generated by Django 2.1.5 on 2019-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0003_auto_20190329_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('A', 'Autre'), ('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True),
        ),
    ]
