# Generated by Django 2.1.5 on 2019-03-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0005_auto_20190330_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('A', 'Do not wish to identify myself'), ('M', 'Homme'), ('F', 'Femme')], default='A', max_length=1),
        ),
    ]
