# Generated by Django 2.1.5 on 2019-04-30 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0006_auto_20190330_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='actiontoken',
            name='expires',
            field=models.DateTimeField(blank=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='actiontoken',
            name='type',
            field=models.CharField(choices=[('account_activation', 'Activation de compte'), ('password_change', 'Change mot de passe')], default=None, max_length=100, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('A', 'Sexe non identifié'), ('M', 'Homme'), ('F', 'Femme')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires',
            field=models.DateTimeField(blank=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification'),
        ),
    ]
