# Generated by Django 2.1.5 on 2019-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0007_auto_20190430_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_agreed_terms_use',
            field=models.BooleanField(default=False, verbose_name="Conditions d'utilisation"),
        ),
    ]
