# Generated by Django 2.1.5 on 2019-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiNomad', '0008_profile_is_agreed_terms_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('A', 'Sexe non identifié'), ('M', 'Homme'), ('F', 'Femme')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_agreed_terms_use',
            field=models.BooleanField(default=False, verbose_name="Conditions d'utilisation"),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
