# Generated by Django 2.1.5 on 2019-01-16 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_remove_address__state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.BooleanField(default=True, verbose_name='Contraintes activity')),
                ('limit_participants', models.PositiveIntegerField(default=0, verbose_name='Limite de participation')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube Link')),
                ('date_start', models.DateTimeField(null=True, verbose_name='Start date')),
                ('date_end', models.DateTimeField(null=True, verbose_name='End date')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Address')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Guides')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ('date_start',),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='activity.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', through='activity.Participation', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
