# Generated by Django 2.1.5 on 2019-01-16 19:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('event', 'participant')},
        ),
    ]
