# Generated by Django 2.1.5 on 2019-01-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190123_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date_start',), 'verbose_name_plural': 'Évènement'},
        ),
        migrations.AlterModelOptions(
            name='eventoption',
            options={'verbose_name_plural': 'Option des évènements'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name_plural': 'Participation aux évènement'},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='date de suppression'),
        ),
        migrations.AlterField(
            model_name='eventoption',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.Event'),
        ),
    ]
