# Generated by Django 2.1.5 on 2019-01-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190116_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='family',
        ),
        migrations.RemoveField(
            model_name='event',
            name='limit_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='youtube_link',
        ),
    ]
