# Generated by Django 2.1.5 on 2019-01-18 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_auto_20190116_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='participant',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('event', 'user')},
        ),
    ]
