# Generated by Django 2.1.5 on 2019-01-21 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20190118_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_deleted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
