# Generated by Django 2.1.5 on 2019-01-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_event_date_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.BooleanField(default=True)),
                ('limit_participant', models.PositiveIntegerField(default=0, verbose_name='number of limit participants')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Event')),
            ],
            options={
                'verbose_name_plural': 'EventOptions',
            },
        ),
    ]
