# Generated by Django 2.1.5 on 2019-01-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_eventoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoption',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='options',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='activity.EventOption'),
            preserve_default=False,
        ),
    ]
