# Generated by Django 2.1.5 on 2019-01-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20190121_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='options',
            new_name='option',
        ),
    ]
