# Generated by Django 2.1.5 on 2019-03-08 14:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(verbose_name='duration')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])])),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('is_deleted', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0, 0, 127325, tzinfo=utc), verbose_name='Date de suppression')),
                ('is_actived', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0, 0, 127325, tzinfo=utc), verbose_name='visible')),
                ('genres', models.ManyToManyField(related_name='videos', to='video.Genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owners')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ('is_created',),
            },
        ),
    ]
