# Generated by Django 2.1.5 on 2019-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genres', to='video.Genre', verbose_name='genres'),
        ),
    ]
