# Generated by Django 2.1.5 on 2019-02-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
    ]
