# Generated by Django 2.1.5 on 2019-03-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190329_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='video.Genre'),
        ),
    ]
