# Generated by Django 2.1.5 on 2019-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190219_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='videos', to='video.Genre'),
        ),
    ]
