# Generated by Django 2.1.5 on 2019-02-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190222_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_deleted',
        ),
    ]
