# Generated by Django 2.1.5 on 2019-02-24 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_video_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_actived',
            field=models.DateTimeField(default='1960-01-01', verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_deleted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de suppression'),
            preserve_default=False,
        ),
    ]
