# Generated by Django 2.1.5 on 2019-05-10 18:59

import django.core.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190501_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_agreed_terms_use',
            field=models.BooleanField(default=0, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=video.models.PathAndRename('uploads/videos/2019/05/10'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
