# Generated by Django 2.1.5 on 2019-05-11 06:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20190510_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=video.models.PathAndRename('uploads/videos/2019/05/11'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
    ]
