# Generated by Django 2.1.5 on 2019-05-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20190511_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_agreed_terms_use',
        ),
    ]
