# Generated by Django 2.1.5 on 2019-05-15 03:08

import django.core.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20190511_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['is_created'], 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='file_thumbnail',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(null=True, upload_to=video.models.PathAndRename('uploads/images/videos/2019/05/14'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=video.models.PathAndRename('uploads/videos/2019/05/14'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
