# Generated by Django 2.1.5 on 2019-05-29 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_auto_20190525_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='avatar',
        ),
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to='video.Image', verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='video',
            name='poster_thumbnail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_thumbnail', to='video.Image', verbose_name='Poster thumbnail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(help_text='Les extension acceptées: jpeg, jpg, png', upload_to=video.models.PathAndRename('uploads/images/videos/2019/05/28'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(help_text='Les extension acceptées: mp4, webm', upload_to=video.models.PathAndRename('uploads/videos/2019/05/28'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
