# Generated by Django 2.1.3 on 2019-01-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_address__state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='_state',
        ),
    ]
